<?
$this->headLink()->appendStylesheet($this->baseUrl('yui/build/fonts/fonts-min.css')); 
$this->headLink()->appendStylesheet($this->baseUrl('yui/build/datatable/assets/skins/sam/datatable.css')); 

$this->headScript()->appendFile('yui/build/yahoo-dom-event/yahoo-dom-event.js');
$this->headScript()->appendFile('yui/build/dragdrop/dragdrop-min.js');
$this->headScript()->appendFile('yui/build/element/element-min.js');
$this->headScript()->appendFile('yui/build/datasource/datasource-min.js');
$this->headScript()->appendFile('yui/build/datatable/datatable-min.js');
$this->headScript()->appendFile('yui/build/connection/connection-min.js');
$this->headScript()->appendFile('yui/build/history/history-min.js');
$this->headScript()->appendFile('yui/build/json/json-min.js');

$this->headScript()->appendFile('plupload/javascript/plupload.js');
$this->headScript()->appendFile('plupload/javascript/plupload.html5.js');
$this->headScript()->appendFile('plupload/javascript/plupload.html4.js');

$this->headScript()->appendFile('js/filedrawers.js');
?>

	<body class="yui-skin-sam">
	<div id="head">
		<h1>Filedrawers</h1>
		<ul>
			<li><a href="" class="active" id="homeBtn">Home</a></li>
			<li><a href="/make-webspace/">Web Sites</a></li>
			<li><a href="/help.php">Help</a></li>
			<li><a href="/cgi-bin/logout?http://mfile.umich.edu/">Logout</a></li>
		</ul>
		<div class="clear">&nbsp;</div>
	</div>
	<div id="infoBar">
		<ul id="infoMenu">
			<li><a href=".." id="goUp">Go Up &uarr;</a></li>
			<li><a href="." id="refresh">Refresh</a></li>
		</ul>
		<div id="notifyArea">			
			<div id="location">
                            <span id="currentLocation">
                                Service: <span id="currentLocationService"></span>
                                Location: <span id="currentLocationPath"></span>
                                <button id="currentLocationChange">Change</button>
                            </span>
                            <form id="changeLocation"><span id="setServicesWrapper"></span>
                                <label for="changeLocationNewPath">Location: </label><input type="text" name="changeLocationNewPath" id="changeLocationNewPath" size="50" />
                                <span id="changeLocationControls">
                                    <button id="changeLocationGo" type="submit">Go</button>
                                    <button id="changeLocationCancel">Cancel</button>
                                </span>
                            </form>
			</div>
			<span id="spinner">&nbsp;<img src="images/ajax-loader.gif" /></span>
			<span id="loadingTxt">&nbsp;Loading...</span>
			<span id="cancelBtn">&nbsp;<input type="button" value="Cancel" /></span>
		</div>
		<div class="clear">&nbsp;</div>
	</div>
	<div id="sidebar">
		<div id="inspector">
			<h3>Folder Properties</h3>
			<div id="selectedItem" style="background-image: url('/images/folder.gif');"></div>
			<h4>Actions</h4>
			<ul id="actionList">
				<li><a href="#upload" class="expandable">Upload File(s)</a></li>
				<li><a href="#cut">Cut Selected Item(s)</a></li>
				<li><a href="#copy">Copy Selected Item(s)</a></li>
				<li><a href="#paste">Paste to This Folder</a></li>
				<li><a href="#del">Delete Selected Item(s)</a></li>
				<li><a href="#createFolder" class="expandable">Create a New Folder</a></li>
				<li><a href="#rename">Rename Selected Item</a></li>
				<li><a href="#permissions">Set Permissions for Folder</a></li>
				<? //<li><a href="#favorites" class="global expandable">Favorite Locations</a></li> ?>
			</ul>
			<div id="itemInfo"></div>
			<h4>View Options</h4>
			<ul>
				<li><a href="#showHidden" class="global" id="hidnFilesCtrl">Show Hidden Files</a></li>
			</ul>
		</div>
		<div id="version">filedrawers version <span id="versionNumber"></span></div>
	</div>
	<div id="feedback"></div><div class="clear"></div>
	
	<div id="contentHolder">
		<div id="content">		
			<div id="fileList"></div>
		</div>
		<div id="favsList">
            <a href="#add"><img id="addBtn" src="images/add.png" /></a>
			<h3>Favorites</h3>
			<div id="favsLinks">
			</div>
		</div>
		<div class="clear">&nbsp;</div>
	</div>	
	
	<div id="favorites" class="expandItem">
		<div class="hd"> <a href="#close">[X]</a>
			<h2>My Favorite Locations</h2>
		</div>
		<div class="bd">
			<div id="favMenu"><a href="#viewFav" class="sel">View</a> | <a href="#addFav">Add</a> | <a href="#editFav">Edit</a></div>
			<div id="viewFav">
				<p>Go to a favorite location:</p>
				<div class="tabContent">&nbsp;</div>
			</div>
			<form action="#" method="post" name="addFav" id="addFav">
				<p>Enter a name and click 'Add' to add the current location to your favorites.</p>
				<input type="text" name="selectedItems" size="18" />
				<p align="center">
					<input type="hidden" name="formKey" value="c0c17487e741591fdcad1e95aa43d2ad" />
					<input type="submit" name="command" value="Add" />
				</p>
			</form>
			<form action="#" method="post" name="editFav" id="editFav">
				<div class="tabContent">&nbsp;</div>
				<p align="center">
					<input type="hidden" name="formKey" value="c0c17487e741591fdcad1e95aa43d2ad" />
					<input type="submit" name="command" value="Save" />
				</p>
			</form>
		</div>
	</div>
	<div id="permissions" class="expandItem">
		<div class="hd"> <a href="#close">[X]</a>
			<h2>Permissions Manager</h2>
		</div>
		<div class="bd">
			<form name="acl" id="acl" method="post" action="#">
				<input type="hidden" name="formKey" value="c0c17487e741591fdcad1e95aa43d2ad">
				<div id="permissionsBox">
					<table>
						<thead>
							<tr>
								<th width="185px">Normal Rights for $DIRECTORY</th>
								<th>lookup</th>
								<th>read</th>
								<th>write</th>
								<th>insert</th>
								<th>delete</th>
								<th>lock</th>
								<th>admin</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>sample pts group 1
									<input type="hidden" name="nrm[umweb:servers][]" value=" " /></td>
								<td><input type="checkbox" name="nrm[umweb:servers][]" value="l" checked="checked" /></td>
								<td><input type="checkbox" name="nrm[umweb:servers][]" value="r" /></td>
								<td><input type="checkbox" name="nrm[umweb:servers][]" value="w" /></td>
								<td><input type="checkbox" name="nrm[umweb:servers][]" value="i" /></td>
								<td><input type="checkbox" name="nrm[umweb:servers][]" value="d" /></td>
								<td><input type="checkbox" name="nrm[umweb:servers][]" value="k" /></td>
								<td><input type="checkbox" name="nrm[umweb:servers][]" value="a" /></td>
							</tr>
							<tr>
								<td>sample pts group 2
									<input type="hidden" name="nrm[system:anyuser][]" value=" " /></td>
								<td><input type="checkbox" name="nrm[system:anyuser][]" value="l" checked="checked" /></td>
								<td><input type="checkbox" name="nrm[system:anyuser][]" value="r" /></td>
								<td><input type="checkbox" name="nrm[system:anyuser][]" value="w" /></td>
								<td><input type="checkbox" name="nrm[system:anyuser][]" value="i" /></td>
								<td><input type="checkbox" name="nrm[system:anyuser][]" value="d" /></td>
								<td><input type="checkbox" name="nrm[system:anyuser][]" value="k" /></td>
								<td><input type="checkbox" name="nrm[system:anyuser][]" value="a" /></td>
							</tr>
							<tr>
								<td>joshfiel
									<input type="hidden" name="nrm[joshfiel][]" value=" " /></td>
								<td><input type="checkbox" name="nrm[joshfiel][]" value="l" /></td>
								<td><input type="checkbox" name="nrm[joshfiel][]" value="r" /></td>
								<td><input type="checkbox" name="nrm[joshfiel][]" value="w" /></td>
								<td><input type="checkbox" name="nrm[joshfiel][]" value="i" /></td>
								<td><input type="checkbox" name="nrm[joshfiel][]" value="d" /></td>
								<td><input type="checkbox" name="nrm[joshfiel][]" value="k" /></td>
								<td><input type="checkbox" name="nrm[joshfiel][]" value="a" checked="checked" /></td>
							</tr>
							<tr>
								<td><input type="text" name="nrm_add_name" length="40" maxlength="40" value="" /></td>
								<td><input type="checkbox" name="nrm[nrm_add][]" value="l" /></td>
								<td><input type="checkbox" name="nrm[nrm_add][]" value="r" /></td>
								<td><input type="checkbox" name="nrm[nrm_add][]" value="w" /></td>
								<td><input type="checkbox" name="nrm[nrm_add][]" value="i" /></td>
								<td><input type="checkbox" name="nrm[nrm_add][]" value="d" /></td>
								<td><input type="checkbox" name="nrm[nrm_add][]" value="k" /></td>
								<td><input type="checkbox" name="nrm[nrm_add][]" value="a" /></td>
							</tr>
						</tbody>
						<thead>
							<tr>
								<th width="185px">Negative Rights for
									AAAtest8</th>
								<th>lookup</th>
								<th>read</th>
								<th>write</th>
								<th>insert</th>
								<th>delete</th>
								<th>lock</th>
								<th>admin</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td><input type="text" name="neg_add_name" length="40" maxlength="40" value="" /></td>
								<td><input type="checkbox" name="neg[neg_add][]" value="l" /></td>
								<td><input type="checkbox" name="neg[neg_add][]" value="r" /></td>
								<td><input type="checkbox" name="neg[neg_add][]" value="w" /></td>
								<td><input type="checkbox" name="neg[neg_add][]" value="i" /></td>
								<td><input type="checkbox" name="neg[neg_add][]" value="d" /></td>
								<td><input type="checkbox" name="neg[neg_add][]" value="k" /></td>
								<td><input type="checkbox" name="neg[neg_add][]" value="a" /></td>
							</tr>
						</tbody>
					</table>
				</div>
				<input name="save" type="submit" class="saveButton" value="Save Permissions" />
			</form>
		</div>
	</div>
	<form id="newFolder" class="expandItem">
		<div class="hd"> <a href="#close">[X]</a>
			<h2>Create a New Folder</h2>
		</div>
		<div class="bd"> <img src="/images/mime/small/folder.gif" width="16" height="16" alt="" />
			<input type="text" name="folderName" id="newFold" size="34" value="Please enter new folder name" onFocus="this.select()" />
			<input type="submit" name="save" value="Create" />
		</div>
	</form>
    
    <form id="upload" class="expandItem" style="display: block; visibility: hidden;" method="post" action="dump.php">
        <div class="hd"> <a href="#close">[X]</a>
            <h2>Upload Files</h2>
        </div>
            <div>
                <div id="filelist">No runtime found.</div><br />
                <input type="submit" id="pickfiles" name="pickfiles" value="Select files"/>
                <input type="submit" id="uploadfiles" name="uploadfiles" value="Upload files"/>
            </div>
    </form>

	<iframe id="yui-history-iframe" src="images/mime/small/0000000dir.gif"></iframe>
	<input id="yui-history-field" type="hidden">

	</body>
		
