<div id="infoBar">
	<ul id="infoMenu">
		<?php if ($this->type == 'file'): ?>
		<li><a href="/download/<?php echo $this->escape($this->path); ?>">Download</a></li>
		<?php endif; ?>
		<li><a href="..">Go Up &uarr;</a></li>
		<li><a href=".">Refresh</a></li>
	</ul>
	<div id="notifyArea"> Location:
		<form id="changeDirForm">
			<?php echo $this->createLinkPath($this->path); ?>
		</form>
	</div>
	<div class="clear">&nbsp;</div>
</div>
<div id="sidebar">
	<div id="inspector">
		<h3>Folder Properties</h3>
		<div id="selectedItem" style="background-image: url(<?php echo $this->baseUrl(); ?>/images/folder.gif);"> <?php echo $this->escape(basename(Router::getInstance()->getFSpath())); ?> </div>
		<h4>Actions</h4>
		<ul id="actionList">
			<li><a href="#upload">Upload File(s)</a></li>
			<li><a href="#cut">Cut Selected Item(s)</a></li>
			<li><a href="#copy">Copy Selected Item(s)</a></li>
			<li><a href="#paste">Paste to This Folder</a></li>
			<li><a href="#del">Delete Selected Item(s)</a></li>
			<li><a href="#createFolder" class="expandable">Create a New Folder</a></li>
			<li><a href="#rename">Rename Selected Item</a></li>
			<li><a href="#permissions">Set Permissions for Folder</a></li>
			<li><a href="#favorites" class="global expandable">Favorite Locations</a></li>
		</ul>
		<div id="itemInfo"></div>
		<h4>View Options</h4>
		<ul>
			<li><a href="#showHidden" class="global">Show Hidden Files</a></li>
		</ul>
	</div>
	<div id="version"> filedrawers version: <?php echo Config::getInstance()->filedrawers['version']; ?></div>
</div>
<div id="content">
	<?php if ($this->files): ?>
	<div id="fileList"></div>
	<?php else: ?>
	<p>The specified file or folder does not exist.</p>
	<?php endif; ?>
</div>
<div id="favorites" class="expandItem">
	<div class="hd"> <a href="#close">[X]</a>
		<h2>My Favorite Locations</h2>
	</div>
	<div class="bd">
		<div id="favMenu"><a href="#viewFav" class="sel">View</a> | <a href="#addFav">Add</a> | <a href="#editFav">Edit</a></div>
		<div id="viewFav">
			<p>Go to a favorite location:</p>
			<div class="tabContent">&nbsp;</div>
		</div>
		<div id="addFav">
			<div class="tabContent">&nbsp;</div>
		</div>
		<form action="#" method="post" id="editFav">
			<div class="tabContent">&nbsp;</div>
		</form>
	</div>
</div>
<div id="permissions" class="expandItem">
	<div class="titlebar"> <a href="#close">[X]</a>
		<h2>Permissions Manager</h2>
	</div>
	<!--<iframe name="perpanel" id="permpanel" scrolling="no" src="/perm_manager.php?target={$path_url}" frameborder="0"></iframe>-->
</div>
<form id="newFolder" class="expandItem">
	<div class="hd"> <a href="#close">[X]</a>
		<h2>Create a New Folder</h2>
	</div>
	<div class="bd"> <img src="/images/mime/small/folder.gif" width="16" height="16" alt="" />
		<input type="text" name="folderName" id="newFold" size="34" value="Please enter a name for your new folder." />
		<input type="submit" name="save" value="Create" />
	</div>
</form>
<form name="upload2" id="upload" class="expandItem" style="display: none;" enctype="multipart/form-data" action="/mfile-bin/upload.cgi" method="post">
	<div class="titlebar"> <a href="javascript:closeItem('uploadCtrl','upload');document.getElementById('upload').reset();">[X]</a>
		<h2>Upload Files to AFS</h2>
	</div>
	<input type="hidden" name="sessionid" id="sessionid" value="" />
	<input type="hidden" name="path" id="uploadpath" value="" />
	<input type="hidden" name="returnToURI" id="returnToURI" value="" />
	<input type="hidden" name="overwrite_file" id="overwrite_file" value="" />
	<ul>
		<li id="file1">
			<input type="file" name="file" />
			<p><a href="javascript:toggleDisplay('file2');">Add Another File</a></p>
		</li>
	</ul>
	<div class="uploadctrl" id="uploadctrl"> Overwrite files during upload?
		<input type="checkbox" name="overwrite_box" id="overwrite_box" onclick="processClobberCheckbox();" />
		<input type="button" name="upload" value="Upload File(s)" onclick="uploadloopcnt=0; ajaxupload();" />
		&nbsp;&nbsp; </div>
	<div id="lbtop">
		<div id="lbinner"></div>
		<table width="100%">
			<tr>
				<td id="fileinfo"></td>
				<td align="right" id="lbpercent"></td>
			</tr>
		</table>
	</div>
</form>
<?php $this->render('filemanager_js.phtml'); ?>
<script type="application/javascript">
var username = "<?php echo Auth::getInstance()->getUsername(); ?>";
var baseUrl = "<?php echo Router::getBaseUrl(); ?>";
<?php if ($this->files): ?>
YAHOO.util.Event.addListener(window, "load", FD.FileManager, <?php echo json_encode($this->files); ?>);
//YAHOO.util.Event.addListener(window, "load", Filedrawers.FileInspector.init);
<?php endif; ?>
</script>
