<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>filedrawers: afs file management</title>
<link href="<?php echo $this->baseUrl(); ?>/css/filedrawers.css" rel="stylesheet" type="text/css" />
<link href="http://yui.yahooapis.com/2.8.0r4/build/datatable/assets/skins/sam/datatable.css" rel="stylesheet" type="text/css" />
</head>
<body class="yui-skin-sam">
<div id="head">
	<h1>Filedrawers</h1>
	<ul>
		<?php if ($this->homeSelected): ?>
		<li><a href="#" class="active">Home</a></li>
		<?php else: ?>
		<li><a href="/">Home</a></li>
		<?php endif; ?>
		<li><a href="/make-webspace/">Web Sites</a></li>
		<li><a href="/help.php">Help</a></li>
		<li><a href="/cgi-bin/logout?http://mfile.umich.edu/">Logout</a></li>
	</ul>
	<div class="clear">&nbsp;</div>
</div>
