<div id="content">
<h2>Listing Files</h2>
<br/>
<h3>Arguments</h3>
<ul>
    <li>path: The path to the directory to be listed</li>
    <li>xml or json: The format of the output</li>
    <li>friendly: Converty bytes and dates into human readable formats</li>
    <li>offset: How many files to skip before starting the list</li>
    <li>limit: How many total files to return maximum</li>
</ul>
<br/>
<h3>Examples (replace /u/s/user)</h3>
<ul>
    <li><a href="list/?json&path=/afs/umich.edu/user/u/s/user&limit=3&offset=3">webservices/list/?json&path=/afs/umich.edu/user/u/s/user&limit=3&offset=3</li>
    <li><a href="list/?xml&path=/afs/umich.edu/user/u/s/user&offset=3&friendly">webservices/list/?xml&path=/afs/umich.edu/user/u/s/user&offset=3&friendly</li>
</ul>

</div>
