<?php echo $this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php
	$this->headLink()->appendStylesheet($this->baseUrl('/css/filedrawers.css'));
        //$this->headLink()->appendStylesheet('http://yui.yahooapis.com/2.8.0r4/build/logger/assets/skins/sam/logger.css');
        //$this->headLink()->appendStylesheet('/css/datatable.css');
	$this->headTitle($this->title);

	echo $this->headMeta() . "\n";
	echo $this->headLink() . "\n";
	echo $this->headScript() . "\n";
	echo $this->headTitle() . "\n";
?>
</head>
<body class="yui-skin-sam">
<div id="head">
	<h1>Filedrawers</h1>
	<ul>
		<?php if ($this->homeSelected): ?>
		<li><a href="#" class="active">Home</a></li>
		<?php else: ?>
		<li><a href="/">Home</a></li>
		<?php endif; ?>
		<li><a href="/make-webspace/">Web Sites</a></li>
		<li><a href="/help.php">Help</a></li>
		<li><a href="/cgi-bin/logout?http://mfile.umich.edu/">Logout</a></li>
	</ul>
	<div class="clear">&nbsp;</div>
</div>
<?php echo $this->layout()->content;?>
</body>
<script type="text/javascript">
var webAppVersion = <?= ( int ) Zend_Registry::get( 'webAppVersion' ) ?>;
</script>
</html>
