<tr>
	<td><?php echo $this->escape($this->type); ?></td>
	<td><?php echo $this->escape($this->filename); ?></td>
	<td><?php echo $this->escape($this->modTime); ?></td>
	<td><?php echo $this->escape($this->size); ?></td>
	<td><?php echo $this->escape($this->mimeImage); ?></td>
	<td><?php echo $this->escape((string) $this->perms); ?></td>
	<td><?php echo $this->escape($this->mimeType); ?></td>
</tr>
