<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8"/>

<script type="text/javascript" src="../plupload/javascript/plupload.full.js"></script>
<script type="text/javascript" src="../plupload/javascript/plupload.html5.js"></script>
<script type="text/javascript" src="../plupload/javascript/plupload.html4.js"></script>

<!-- <script type="text/javascript"  src="http://getfirebug.com/releases/lite/1.2/firebug-lite-compressed.js"></script> -->

</head>
<body>

<?
if ( !isset($_GET['service']) or !isset($_GET['path']) ) {
    echo '<form action="upload" method="'.$_SERVER["REQUEST_URI"].'">';
    echo '<input name="service" />';
    echo '<input name="path" />';
    echo '<input type="submit" name="go to plupload" />';
    echo '</form>';
} else { ?> 


	<div id="uploader">
    <p>Upload Files:</p>

    <div id="filelist"> </div>
    <br />

    <a id="pickfiles" href="javascript:;">Add Files</a>
    <a id="uploadfiles" href="javascript:;">Start Upload</a>

	</div>
<? } ?>

<script type="text/javascript">
var settings = {
     runtimes: 'html5,html4',
     multipart: false,
	url : '<? echo $_SERVER["REQUEST_URI"] ?>'
};

var uploader = new plupload.Uploader(settings);
// initialize to get features object
uploader.init();
    
if (!uploader.features.html5) {
    settings.multipart = true;
    settings.runtimes = 'html5,html4';
}

// now create the real instance with all settings
settings.browse_button = 'pickfiles';
uploader = new plupload.Uploader(settings);
uploader.init();

uploader.bind('FilesAdded', function(up, files) {
// loop through the files array
    for (var i in files) {
         document.getElementById('filelist').innerHTML += '<div id="' + files[i].id + '">' + files[i].name + ' (' + plupload.formatSize(files[i].size) + ') <b></b></div>';
    }
});

uploader.bind('UploadProgress', function(up, file) {
    document.getElementById(file.id).getElementsByTagName('b')[0].innerHTML = '<span>' + file.percent + "%</span>";
});

uploader.bind('Error', function(up, args) {
    alert(args.code + ': ' + args.message);
});

document.getElementById('uploadfiles').onclick = function() {
    uploader.start();
};

</script>
</body>
</html>
